branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - set QT5=C:\Qt\5.12.6\mingw73_32
  - set MINGW=C:\Qt\Tools\mingw730_32
  - set PATH=%MINGW%\bin;%QT5%\bin;%PATH%
build_script:
  - qmake acitemcheatmaker.pro
  - mingw32-make
after_build:
  - windeployqt -qmldir . .\release\acitemcheatmaker.exe
  - cmd: cp items.json .\release\
  - cmd: cp %QT5%\bin\libgcc_s_dw2-1.dll .\release\
  - cmd: cp %QT5%\bin\libstdc++-6.dll .\release\
  - cmd: cp %QT5%\bin\libwinpthread-1.dll .\release\
  - rm release/*.o
  - rm release/*.cpp
  
artifacts:
  - path: release
    type: zip
